basePath: /api/v1
definitions:
  interfaces.Arg:
    properties:
      description:
        type: string
      identifier:
        type: string
      name:
        type: string
      required:
        type: boolean
    type: object
  interfaces.Command:
    properties:
      action:
        type: string
      activator:
        type: string
      args:
        items:
          $ref: '#/definitions/interfaces.Arg'
        type: array
      description:
        type: string
      id:
        type: integer
      roles:
        items:
          $ref: '#/definitions/interfaces.Role'
        type: array
      steps:
        items:
          $ref: '#/definitions/interfaces.Step'
        type: array
      uniqueId:
        type: string
    type: object
  interfaces.CreateCommand:
    properties:
      action:
        type: string
      activator:
        type: string
      args:
        items:
          $ref: '#/definitions/interfaces.Arg'
        type: array
      description:
        type: string
      roles:
        items:
          type: string
        type: array
      steps:
        items:
          $ref: '#/definitions/interfaces.Step'
        type: array
    type: object
  interfaces.Param:
    properties:
      key:
        type: string
      type:
        type: string
      value:
        type: string
    type: object
  interfaces.Role:
    properties:
      description:
        type: string
      level:
        type: integer
      name:
        type: string
    type: object
  interfaces.Step:
    properties:
      name:
        type: string
      params:
        items:
          $ref: '#/definitions/interfaces.Param'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for console management.
  title: Console API
  version: "1.0"
paths:
  /commands:
    post:
      description: Create a new command to be used in application
      parameters:
      - description: Command JSON
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/interfaces.CreateCommand'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/interfaces.Command'
      summary: Create a new Command
      tags:
      - commands
swagger: "2.0"
