name: Build and Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.17'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run vet
      run: go vet ./...

    - name: Run tests
      run: go test -v ./...
      env:
        API_SECRET: "test_secret"
        TOKEN_HOUR_LIFESPAN: 1

    - name: Build
      run: go build -v ./...

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      run: docker build -t otontech-console-api:${{ github.sha }} .
      
    - name: Test Docker image
      run: |
        docker run --rm -d --name test-container -p 8081:8081 otontech-console-api:${{ github.sha }}
        sleep 5
        docker logs test-container
        docker stop test-container